<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command_loader' shared service.

return $this->services['console.command_loader'] = new \Symfony\Component\Console\CommandLoader\ContainerCommandLoader(new \Symfony\Component\DependencyInjection\ServiceLocator(array('console.command.about' => function (): \Symfony\Bundle\FrameworkBundle\Command\AboutCommand {
    return ($this->privates['console.command.about'] ?? $this->load('getConsole_Command_AboutService.php'));
}, 'console.command.assets_install' => function (): \Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand {
    return ($this->privates['console.command.assets_install'] ?? $this->load('getConsole_Command_AssetsInstallService.php'));
}, 'console.command.cache_clear' => function (): \Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand {
    return ($this->privates['console.command.cache_clear'] ?? $this->load('getConsole_Command_CacheClearService.php'));
}, 'console.command.cache_pool_clear' => function (): \Symfony\Bundle\FrameworkBundle\Command\CachePoolClearCommand {
    return ($this->privates['console.command.cache_pool_clear'] ?? $this->load('getConsole_Command_CachePoolClearService.php'));
}, 'console.command.cache_pool_delete' => function (): \Symfony\Bundle\FrameworkBundle\Command\CachePoolDeleteCommand {
    return ($this->privates['console.command.cache_pool_delete'] ?? $this->load('getConsole_Command_CachePoolDeleteService.php'));
}, 'console.command.cache_pool_prune' => function (): \Symfony\Bundle\FrameworkBundle\Command\CachePoolPruneCommand {
    return ($this->privates['console.command.cache_pool_prune'] ?? $this->load('getConsole_Command_CachePoolPruneService.php'));
}, 'console.command.cache_warmup' => function (): \Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand {
    return ($this->privates['console.command.cache_warmup'] ?? $this->load('getConsole_Command_CacheWarmupService.php'));
}, 'console.command.config_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\ConfigDebugCommand {
    return ($this->privates['console.command.config_debug'] ?? $this->load('getConsole_Command_ConfigDebugService.php'));
}, 'console.command.config_dump_reference' => function (): \Symfony\Bundle\FrameworkBundle\Command\ConfigDumpReferenceCommand {
    return ($this->privates['console.command.config_dump_reference'] ?? $this->load('getConsole_Command_ConfigDumpReferenceService.php'));
}, 'console.command.container_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand {
    return ($this->privates['console.command.container_debug'] ?? $this->load('getConsole_Command_ContainerDebugService.php'));
}, 'console.command.debug_autowiring' => function (): \Symfony\Bundle\FrameworkBundle\Command\DebugAutowiringCommand {
    return ($this->privates['console.command.debug_autowiring'] ?? $this->load('getConsole_Command_DebugAutowiringService.php'));
}, 'console.command.event_dispatcher_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\EventDispatcherDebugCommand {
    return ($this->privates['console.command.event_dispatcher_debug'] ?? $this->load('getConsole_Command_EventDispatcherDebugService.php'));
}, 'console.command.router_debug' => function (): \Symfony\Bundle\FrameworkBundle\Command\RouterDebugCommand {
    return ($this->privates['console.command.router_debug'] ?? $this->load('getConsole_Command_RouterDebugService.php'));
}, 'console.command.router_match' => function (): \Symfony\Bundle\FrameworkBundle\Command\RouterMatchCommand {
    return ($this->privates['console.command.router_match'] ?? $this->load('getConsole_Command_RouterMatchService.php'));
}, 'console.command.yaml_lint' => function (): \Symfony\Bundle\FrameworkBundle\Command\YamlLintCommand {
    return ($this->privates['console.command.yaml_lint'] ?? $this->load('getConsole_Command_YamlLintService.php'));
}, 'maker.auto_command.make_auth' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_auth'] ?? $this->load('getMaker_AutoCommand_MakeAuthService.php'));
}, 'maker.auto_command.make_command' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_command'] ?? $this->load('getMaker_AutoCommand_MakeCommandService.php'));
}, 'maker.auto_command.make_controller' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_controller'] ?? $this->load('getMaker_AutoCommand_MakeControllerService.php'));
}, 'maker.auto_command.make_crud' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_crud'] ?? $this->load('getMaker_AutoCommand_MakeCrudService.php'));
}, 'maker.auto_command.make_entity' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_entity'] ?? $this->load('getMaker_AutoCommand_MakeEntityService.php'));
}, 'maker.auto_command.make_fixtures' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_fixtures'] ?? $this->load('getMaker_AutoCommand_MakeFixturesService.php'));
}, 'maker.auto_command.make_form' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_form'] ?? $this->load('getMaker_AutoCommand_MakeFormService.php'));
}, 'maker.auto_command.make_functional_test' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_functional_test'] ?? $this->load('getMaker_AutoCommand_MakeFunctionalTestService.php'));
}, 'maker.auto_command.make_migration' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_migration'] ?? $this->load('getMaker_AutoCommand_MakeMigrationService.php'));
}, 'maker.auto_command.make_serializer_encoder' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_serializer_encoder'] ?? $this->load('getMaker_AutoCommand_MakeSerializerEncoderService.php'));
}, 'maker.auto_command.make_subscriber' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_subscriber'] ?? $this->load('getMaker_AutoCommand_MakeSubscriberService.php'));
}, 'maker.auto_command.make_twig_extension' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_twig_extension'] ?? $this->load('getMaker_AutoCommand_MakeTwigExtensionService.php'));
}, 'maker.auto_command.make_unit_test' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_unit_test'] ?? $this->load('getMaker_AutoCommand_MakeUnitTestService.php'));
}, 'maker.auto_command.make_user' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_user'] ?? $this->load('getMaker_AutoCommand_MakeUserService.php'));
}, 'maker.auto_command.make_validator' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_validator'] ?? $this->load('getMaker_AutoCommand_MakeValidatorService.php'));
}, 'maker.auto_command.make_voter' => function (): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
    return ($this->privates['maker.auto_command.make_voter'] ?? $this->load('getMaker_AutoCommand_MakeVoterService.php'));
}, 'twig.command.debug' => function (): \Symfony\Bridge\Twig\Command\DebugCommand {
    return ($this->privates['twig.command.debug'] ?? $this->load('getTwig_Command_DebugService.php'));
}, 'twig.command.lint' => function (): \Symfony\Bundle\TwigBundle\Command\LintCommand {
    return ($this->privates['twig.command.lint'] ?? $this->load('getTwig_Command_LintService.php'));
})), array('about' => 'console.command.about', 'assets:install' => 'console.command.assets_install', 'cache:clear' => 'console.command.cache_clear', 'cache:pool:clear' => 'console.command.cache_pool_clear', 'cache:pool:prune' => 'console.command.cache_pool_prune', 'cache:pool:delete' => 'console.command.cache_pool_delete', 'cache:warmup' => 'console.command.cache_warmup', 'debug:config' => 'console.command.config_debug', 'config:dump-reference' => 'console.command.config_dump_reference', 'debug:container' => 'console.command.container_debug', 'debug:autowiring' => 'console.command.debug_autowiring', 'debug:event-dispatcher' => 'console.command.event_dispatcher_debug', 'debug:router' => 'console.command.router_debug', 'router:match' => 'console.command.router_match', 'lint:yaml' => 'console.command.yaml_lint', 'debug:twig' => 'twig.command.debug', 'lint:twig' => 'twig.command.lint', 'make:auth' => 'maker.auto_command.make_auth', 'make:command' => 'maker.auto_command.make_command', 'make:controller' => 'maker.auto_command.make_controller', 'make:crud' => 'maker.auto_command.make_crud', 'make:entity' => 'maker.auto_command.make_entity', 'make:fixtures' => 'maker.auto_command.make_fixtures', 'make:form' => 'maker.auto_command.make_form', 'make:functional-test' => 'maker.auto_command.make_functional_test', 'make:serializer:encoder' => 'maker.auto_command.make_serializer_encoder', 'make:subscriber' => 'maker.auto_command.make_subscriber', 'make:twig-extension' => 'maker.auto_command.make_twig_extension', 'make:unit-test' => 'maker.auto_command.make_unit_test', 'make:validator' => 'maker.auto_command.make_validator', 'make:voter' => 'maker.auto_command.make_voter', 'make:user' => 'maker.auto_command.make_user', 'make:migration' => 'maker.auto_command.make_migration'));
